### ISSUE TITLE
reaction roles

### ISSUE THREAD

**Issue by satyamedh** [EclipseDiscordBot/EclipseDiscordBot#36]

**Comment by Zapd0s** [comment]
nope its a complicated one:
To create a "reaction roles" system you need to wait on reactions on older messages- which will not be in the 5000(default) long cache discord.py maintains- and if a message is not in the cache, on_reaction_add will not dispatch for reactions added to that message.

To resolve this, on the async branch you can use on_socket_raw_receive and parse the events "manually", and get the "raw event" that way- see ?tag on_socket_raw_receive, which will provide you with several dicts with relevant IDs.
On the rewrite branch, on_raw_reaction_add is provided, which will trigger for all reactions regardless of cache, and provides you a RawReactionActionEvent object containing relevant IDs.

Use the IDs in these objects to filter out reactions relevant to messages and emojis you care about, and get relevant role/member objects.

**Comment by satyamedh** [comment]
Dude, lets wait for rewrite then!


I will try the async branch anyway lmao

**Comment by satyamedh** [comment]
Ehhhhh @Zapd0s 


isnt async branch 2 years old at this point?

**Comment by satyamedh** [comment]
on_socket_raw_receive
:keke:

**Comment by satyamedh** [comment]
DONE!
